### ISSUE TITLE
Conteúdo do curso

### ISSUE THREAD

**Issue by dutofanim** [dutofanim/cursoJavaScript#1]
- [ ] ***Introdução ao Curso***
  - [ ] Assistir ao primeiro vídeo

---
- [ ] ***Módulo A - Conhecendo o Javascript***
  - [ ] Conhecendo o Javascript
  - [ ] O que o Javascript é capaz de fazer? Curso Javascript aula #1
  - [ ] Javascrip: como chegamos até aqui? Curso Javascript aula #2
  - [ ] Dando os primeiros passos. Curso Javascript aula #3
  - [ ] Criando seu primeiro script. Curso Javascript aula #4
---
- [ ] ***Módulo B - Comandos básicos do Javascript***
  - [ ] Variáveis e Tipos Primitivos. Curso Javascript aula #5
  - [ ] Tratamento de dados. Curso Javascript aula #6
  - [ ] Operadores parte 1. Curso Javascript aula #7
  - [ ] Operadores parte 2. Curso Javascript aula #8
---
- [ ] ***Módulo C - Entendendo o DOM***
  - [ ] Introdução ao DOM. Curso javascript #9
  - [ ] Eventos DOM. Curso Javascript #10
---
- [ ] ***Módulo D - Condições em Javascript***
  - [ ] Condições parte 1. Curso Javascript #11
  - [ ] Condições parte 2. Curso Javascript #12
  - [ ] Exercícios parte 1. Curso Javascript
  - [ ] Exercícios parte 2. Curso Javascript
  - [ ] Exercícios parte 3. Curso Javascript
---
- [ ] ***Módulo E - Repetições em Javascript***
  - [ ] Repetições parte 1. Curso Javascript #13
  - [ ] Repetições parte 2. Curso Javascript #14
  - [ ] Exercícios parte 4. Curso Javascript
  - [ ] Exercícios parte 5. Curso Javascript
  - [ ] Exercícios parte 6. Curso Javascript
---
- [ ] ***Módulo F - Avançando os estudos em Javascript***
  - [ ] Variáveis Compostas. Curso Javascript #15
  - [ ] Funções. Curso Javascript #16
  - [ ] Exercícios parte 7. Curso Javascript
  - [ ] Exercícios parte 7. Curso Javascript
  - [ ] Próximos Passos. Curso Javascript #17
---
